"""add_role

Revision ID: 53720e2aa49a
Revises: 3c2a85b0a996
Create Date: 2024-05-07 10:09:25.181329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53720e2aa49a'
down_revision: Union[str, None] = '3c2a85b0a996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
      op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False, server_default=''))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
